//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndustryCodes.Database.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassificationCode
    {
        public int ID { get; set; }
        public string INDUSTRY_SECTOR { get; set; }
        public string INDUSTRY_SUBSECTOR { get; set; }
        public Nullable<int> NORTH_AMERICAN_CODE { get; set; }
        public string NORTH_AMERICAN_DESCRIPTION { get; set; }
        public Nullable<int> STANDARD_CODE { get; set; }
        public string STANDARD_DESCRIPTION { get; set; }
        public Nullable<int> KIND_CODE { get; set; }
        public string KIND_CODE_DESCRIPTION { get; set; }
        public Nullable<int> NORTH_AMERICAN_CODE_2002 { get; set; }
        public string NORTH_AMERICAN_DESCRIPTION_2002 { get; set; }
    }
}
